### ISSUE TITLE
Default example doesnt build with v0.7.0 under windows with msvc as compiler

### ISSUE THREAD

**Issue by llytaii** [zerodaycode/Zork#87]
### Description
After initializing a new project on windows using msvc, trying to build it fails because of a wrongly escaped path

### Steps to reproduce

1. zork++ new test --compiler msvc
2. cd test
3. zork++ run
4. the following error message appears:
```
c1xx: fatal error C1083: Datei (Quelle) kann nicht geöffnet werden: "./cryptogram/ifc\math.ixx": No such file or directory
[2023-03-03T12:56:40.038Z ERROR zork] [FAILED] - The process failed, taking a total time in complete of: 3588 ms

       0: Failed to build the project for the config file: "zork_msvc.toml"
       1: Ending the program, because the build of: "./cryptogram/ifc\\math.ixx" wasn't ended successfully

    Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
    Run with RUST_BACKTRACE=full to include source snippets.
Error:
   0: Failed to build the project for the config file: "zork_msvc.toml"
   1: Ending the program, because the build of: "./cryptogram/ifc\\math.ixx" wasn't ended successfully

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

### Environment
OS: Windows 11 Pro 22H2
Compiler: MSVC

**Comment by Pyzyryab** [comment]
Hello @llytaii 

The issue is your second step. You don't need to `cd` into the project to actually run the example project. `Zork++` examples are designed (for now) for work one directory above of the project's root (if you carefully look at the `zork.toml` config file.

Solution is quite simple. Run the installed `Zork++` binary from the parent directory of the newly created project, or, if you desire, change the path(s) in the `Zork++` config file provided.
